# Generated by Django 2.2.3 on 2019-07-27 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comm_number', models.CharField(max_length=200)),
                ('status_control', models.IntegerField(default=0)),
                ('status_connection', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ErrorHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LastError', models.CharField(max_length=200)),
                ('elevator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Elevator')),
            ],
        ),
    ]
